title: Hwanhee Cho
url: "https://wheee88.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://wheee88.github.io"
footer_text: "Page design by Hwanhee Cho"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
